// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package sv1

import (
	"github.com/bantla/internal/app/shopping-cart/role/repository/gormrepo"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeRoleService(db *gorm.DB) RoleService {
	roleRepository := gormrepo.NewRoleRepository(db)
	sv1RoleService := newRoleService(roleRepository)
	return sv1RoleService
}
