// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package sv1

import (
	gormrepo3 "github.com/bantla/internal/app/shopping-cart/permission/repository/gormrepo"
	"github.com/bantla/internal/app/shopping-cart/role-permission/repository/gormrepo"
	gormrepo2 "github.com/bantla/internal/app/shopping-cart/role/repository/gormrepo"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeRolePermissionService(db *gorm.DB) RolePermissionService {
	rolePermissionRepository := gormrepo.NewRolePermissionRepository(db)
	roleRepository := gormrepo2.NewRoleRepository(db)
	permissionRepository := gormrepo3.NewPermissionRepository(db)
	sv1RolePermissionService := newPermissionService(rolePermissionRepository, roleRepository, permissionRepository)
	return sv1RolePermissionService
}
