// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package role

import (
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeService(db *gorm.DB) Service {
	roleRoleRepository := newRepository(db)
	roleService := newService(roleRoleRepository)
	return roleService
}
