// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package v1

import (
	"github.com/bantla/internal/app/shopping-cart/role"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeRoleService(db *gorm.DB) RoleService {
	repository := role.NewRepository(db)
	v1RoleService := newRoleService(repository)
	return v1RoleService
}
