// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package sv1

import (
	"github.com/bantla/internal/app/shopping-cart/permission/repository/gormrepo"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializePermissionService(db *gorm.DB) PermissionService {
	permissionRepository := gormrepo.NewPermissionRepository(db)
	sv1PermissionService := newPermissionService(permissionRepository)
	return sv1PermissionService
}
